---
title: "Data analysis"
output: html_notebook
---


```{r}
# library(readxl)
# install.Rtools()
# install.packages("tidyr")
# install.packages("ggpubr")
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggpubr)




```

```{r}
base_path <- "C:/Users/trygg/Documents/Master_project" #home
# base_path <- "C:/Users/tryggvisi/Documents/my-awesome-masters-project/"#work
datapath <- "Data/Vindefjallen_data/Vindefjallen_cleaning/Vindefjallen_Granule_processing/1final_measurement_values_v1.csv"
#file_path_final <- "C:/Users/tryggvisi/Documents/my-awesome-masters-project/Data/Vindefjallen_data/Vindefjallen_cleaning/Vindefjallen_Granule_processing/1final_measurement_values_v1.csv"
file_path_final <- file.path(base_path, datapath)

df_final <- read.csv(file_path_final)


columns_to_remove <- c(1,2,3,4,5,6,10,12,13,14,15,17,18,19,20)  # Specify the column numbers you want to remove
df <- df_final[, -columns_to_remove]
colnames(df)[3] <- "snow_depth"
# Remove rows that do not contain numerical values
df <- df[grepl("^\\d+$", df$snow_depth), ]
#convert df$snow_depth to numeric
df$snow_depth <- as.numeric(df$snow_depth)

df$VHVV_ratio <- round(df$point_VH / df$point_VV, 2)
```

```{r}
base_path <- "C:/Users/trygg/Documents/Master_project/" #home
# base_path <- "C:/Users/tryggvisi/Documents/my-awesome-masters-project/"#work
data_path <- "Data/Vindefjallen_data/Vindefjallen_cleaning/exploratory_data_analysis/final_measurements_clean_basic.csv"
file_path_final <- file.path(base_path, data_path)

# Export dataframe to Excel file
#write.xlsx(df_NAna, file = "fullpath_data.xlsx", rowNames = TRUE)
write.csv(df, file = file_path_final, row.names = TRUE)
```


```{r}
#plot data

# apply log values to the data
df$log_snow_depth <- log(df$snow_depth)
df$log_VHVV_ratio <- log(df$VHVV_ratio)

#plot log_snow_depth and log_VHVV_ratio together
plot(df$snow_depth, df$log_VHVV_ratio, main = "Scatterplot of log_snow_depth and log_VHVV_ratio", xlab = "snow_depth", ylab = "log_VHVV_ratio", pch = 19, frame = FALSE)

#plot snow_depth and VHVV_ratio together
plot(df$snow_depth, df$VHVV_ratio, main = "Scatterplot of snow_depth and VHVV_ratio", xlab = "snow_depth", ylab = "VHVV_ratio", pch = 19, frame = FALSE)

```

```{r}
#data tests
shapiro.test(df$point_VH)

#Since the p-value is less than the typical significance level of 0.05, we reject the null hypothesis that the data is normally distributed. This means that the VHVV_ratio data may not follow a normal distribution.

shapiro.test(df$point_VV)
#With such a small p-value (typically denoted as < 0.05), the null hypothesis that the data is normally distributed is rejected. This suggests that the "point_VV" data may not follow a normal distribution.

shapiro.test(df$VHVV_ratio)

#With such a small p-value, much less than the conventional significance level of 0.05, the null hypothesis that the data is normally distributed is rejected. This indicates that the "VHVV_ratio" data likely deviates from a normal distribution.

hist(df$VHVV_ratio, main = "Histogram for VH/VV")

qqnorm(df$VHVV_ratio)
qqline(df$VHVV_ratio, col = 2)


qqnorm(df$VHVV_ratio)
qqline(df$VHVV_ratio)

ggqqplot(df$VHVV_ratio)
```


```{r}
# x <- df$snow_depth
# y <- df$VHVV_ratio
# x <- df$point_VH
# y <- df$point_VV
x <- df$snow_depth
y <- df$log_VHVV_ratio


correlation <- cor.test(x, y, method = "spearman", exact = FALSE, conf.level = 0.95, continuity = TRUE, correct = TRUE)
correlation_kendall <- cor.test(x, y, method = "kendall")

# Print the results
print(correlation_kendall)
# Print the results
print(correlation)
```




